version: '3.8'
services:
    stean:
        container_name: stean
        build: .
        image: mario35/api-stean:latest
        depends_on:
            - db
        environment:            
            DB_IP: db
        ports:
            - "8029:8029"
    db:
        container_name: postgis
        image: postgis/postgis
        ports:
            - "5433:5432"
#        volumes:
#            - data:/data/db
        restart: always
        environment:
            POSTGRES_USER: sensorthings
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: sensorthings
            ALLOW_IP_RANGE: 0.0.0.0/0
#        volumes:
#            - "./data:/var/lib/postgresql/data"
#volumes:
#     data: {}