export enum ENTITIES {    
    Things = 'Things' ,
    FeaturesOfInterest = 'FeaturesOfInterest' ,
    Locations = 'Locations' ,
    HistoricalLocations = 'HistoricalLocations' ,
    locationsHistoricalLocations = 'locationsHistoricalLocations' ,
    ObservedProperties = 'ObservedProperties' ,
    Sensors = 'Sensors' ,
    Datastreams = 'Datastreams' ,
    MultiDatastreams = 'MultiDatastreams' ,
    MultiDatastreamObservedProperties = 'MultiDatastreamObservedProperties' ,
    Observations = 'Observations' ,
    HistoricalObservations = 'HistoricalObservations' ,
    ThingsLocations = 'ThingsLocations' ,
    Decoders = 'Decoders' ,
    Loras = 'Loras' ,
    CreateObservations = 'CreateObservations' ,
    CreateFile = 'CreateFile' ,
    Logs = 'Logs',
    Users = 'Users',
    Configs= 'Configs',
}